import type { Resources } from "./types";

export const resources: Resources[] = [
    {
        id: 1,
        title: "TypeScript Handbook",
        description: "A guide to TypeScript fundamentals and advanced concepts.",
        type: "book",
        status: "available",
        visibility: "public",
    },
    {
        id: 2,
        title: "JavaScript: The Definitive Guide",
        description: "A reference guide for modern JavaScript development.",
        type: "book",
        status: "available",
        visibility: "public",
    },
    {
        id: 3,
        title: "Understanding REST APIs",
        description: "An introduction to REST API concepts and HTTP methods.",
        type: "article",
        status: "available",
        visibility: "public",
    },
    {
        id: 4,
        title: "Introduction to PostgreSQL",
        description: "Learn the fundamentals of PostgreSQL databases.",
        type: "book",
        status: "pending",
        visibility: "public",
    },
    {
        id: 5,
        title: "Web Accessibility Fundamentals",
        description: "Important principles for building accessible websites.",
        type: "article",
        status: "available",
        visibility: "public",
    },
    {
        id: 6,
        title: "Modern CSS Layouts",
        description: "Learn Flexbox, Grid, and modern responsive layouts.",
        type: "video",
        status: "available",
        visibility: "public",
    },
    {
        id: 7,
        title: "Clean Code Principles",
        description: "Practical principles for writing maintainable software.",
        type: "book",
        status: "available",
        visibility: "public",
    },
    {
        id: 8,
        title: "Introduction to Git",
        description: "Learn version control and essential Git commands.",
        type: "video",
        status: "available",
        visibility: "public",
    },
    {
        id: 9,
        title: "Database Design Basics",
        description: "An introduction to designing structured relational databases.",
        type: "article",
        status: "pending",
        visibility: "public",
    },
    {
        id: 10,
        title: "HTTP and Web Fundamentals",
        description: "Understand how browsers and web servers communicate.",
        type: "book",
        status: "archived",
        visibility: "public",
    },
    {
        id: 11,
        title: "Async JavaScript Explained",
        description: "Learn promises, async functions, and await.",
        type: "video",
        status: "available",
        visibility: "public",
    },
    {
        id: 12,
        title: "Understanding JSON",
        description: "Learn how JSON is structured and used in web applications.",
        type: "article",
        status: "available",
        visibility: "public",
    },
    {
        id: 13,
        title: "Node.js Fundamentals",
        description: "An introduction to server-side JavaScript with Node.js.",
        type: "book",
        status: "available",
        visibility: "private",
    },
    {
        id: 14,
        title: "Responsive Web Design",
        description: "Techniques for creating websites that work across devices.",
        type: "video",
        status: "available",
        visibility: "public",
    },
    {
        id: 15,
        title: "SQL Query Optimization",
        description: "Learn techniques for improving SQL query performance.",
        type: "article",
        status: "pending",
        visibility: "private",
    },
    {
        id: 16,
        title: "Object-Oriented Programming",
        description: "Learn the fundamental concepts of object-oriented programming.",
        type: "book",
        status: "archived",
        visibility: "public",
    },
    {
        id: 17,
        title: "Browser Rendering Explained",
        description: "Understand how browsers render HTML, CSS, and JavaScript.",
        type: "video",
        status: "available",
        visibility: "public",
    },
    {
        id: 18,
        title: "Introduction to Type Systems",
        description: "Explore static typing and type systems in programming.",
        type: "article",
        status: "available",
        visibility: "private",
    },
    {
        id: 19,
        title: "Frontend Architecture Patterns",
        description: "Common patterns for organizing frontend applications.",
        type: "book",
        status: "pending",
        visibility: "public",
    },
    {
        id: 20,
        title: "Building Accessible Interfaces",
        description: "Practical techniques for accessible user interfaces.",
        type: "video",
        status: "available",
        visibility: "public",
    },
];